#!/bin/sh

. ./config
EINARC_DIR=$CLIENT_DIR/lib/einarc

mkdir -p src/doc/einarc/xhtml/images
cat >src/doc/einarc/xhtml/manual.page <<__EOF__
---
title: Reference manual
in_menu: false
directory_name: Einarc
--- pipeline:blocks
__EOF__

cp $EINARC_DIR/doc/xhtml/images/*.png src/doc/einarc/xhtml/images

if [ ! -r $EINARC_DIR/doc/xhtml/manual.html ]; then
	echo 'No pre-built Einarc documentation was found. Please go to Einarc directory and run "make doc" there.'
    exit 1
fi

cat $EINARC_DIR/doc/xhtml/manual.html |
	sed -e '
/<?xml version="1.0" encoding="UTF-8"?>/ d;
/<!DOCTYPE html/ d;
s,<html xmlns="http://www.w3.org/1999/xhtml">,,;
s,<head>.*</head>,,;
s,<body>,,;
s,</body>,,;
s,</html>,,;
s,<hr />,,;
s,<h2 class="title"><a id=".*"></a>Einarc: Reference manual</h2>,<h2>Einarc: Reference manual</h2>,;
' >>src/doc/einarc/xhtml/manual.page
